apiVersion: v1
kind: Secret
metadata:
  name: firecrawl-secret
type: Opaque
data:
  OPENAI_API_KEY: ""
  SLACK_WEBHOOK_URL: ""
  LLAMAPARSE_API_KEY: ""
  LOGTAIL_KEY: ""
  BULL_AUTH_KEY: ""
  TEST_API_KEY: ""
  POSTHOG_API_KEY: ""
  POSTHOG_HOST: ""
  SCRAPING_BEE_API_KEY: ""
  STRIPE_PRICE_ID_STANDARD: ""
  STRIPE_PRICE_ID_SCALE: ""
  HYPERDX_API_KEY: ""
  FIRE_ENGINE_BETA_URL: ""
