app = 'firecrawl-dragonfly'
primary_region = 'iad'

[[mounts]]
  source = 'firecrawl_redis'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 6379

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

[[vm]]
  size = 'performance-4x'
  memory = '32gb'

[[metrics]]
  port = 9091
  path = '/metrics'
